### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dash_of_spice-R#58]
Hey Group 5,

Congrats on finishing milestone 3! Seems you now have a lot more of your intended slider functionality working, which is awesome! I think your dashboard is one of the more ambitious ones, but it's starting to come together now. I look forward to the final version! In the meantime, I have a few suggested improvements:
- Replace rank table with bar plot you don't need both. Except for the bar plot, instead of having the rank on the x-axis, have the Happiness score. That will convey all the same info as the table, but more visually. 
- Work on layout, bring country selection dropdown and metric dropdown to both be with the corresponding line plot
- Maybe reconsider how to handle corruption. It seems to be treated as a positive, probably need to flip the order of the countries after you standardize the variables (e.g. if scoring by percentile, change to 1-percentile)
- Happiness score is sometimes greater than 10 and sometimes negative (which is ok, but then you shouldn't cap your color scale at 0-10)
- If you have time, I'd also recommend making the bar plot a stacked bar graph. e.g. something like this: ![stacked barplot](https://i.imgur.com/HKYOA1v.png)
This is probably most easily done using pure plotly rather than ggplotly as in plotly you can calculate the subscores in columns and then follow [this outline](https://plotly.com/r/bar-charts/#stacked-bar-chart) whereas in ggplotly you'd need to do some melting. If you want, you can even put the y-axis labels above the bars following a procedure similar to [this](https://dkane.net/2020/better-horizontal-bar-charts-with-plotly/)

Good luck with your final milestone!

**Comment by rachelywong** [comment]
Hi Chris! 

Thank you for the feedback. We've taken it into consideration, specifically:

- Changed the bar plot to show global average happiness score over the years for specified countries, and if more than one country is selected the happiness score and rank of the selected counties will be compared for 2020
- Layout has been fixed to look more organized!
- Corruption algorithm has been added to change the metric to "Minimal Corruption"
