### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/dash_of_spice-R#7]
In this section, your group should document on what you have implemented in your dashboard so far and explain what is not yet implemented. It is important that you include what you know is not working in your dashboard, so that your TAs can distinguish between features in development and bugs.

This week it is suitable to include some brief thoughts on the experience of implementing the dashboard a second time in another language. You could also mention some feedback you have received and how that has impacted your future planning. This section should be around 300-400 words and the reflection-milestone3.md document should live in your GitHub.com repo in the doc folder.

**Comment by rachelywong** [comment]
done!
