### ISSUE TITLE
Could you use this optimized version of your gif?

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/dash_of_spice-R#82]
Hey @cmmclaug @Saule-Atymtayeva @rachelywong @ChadNeald ! Great job tying your dashboard together, I really like that layout you changed to and the final touches you added! And very high quality gif also, in fact so high quality that the showcase dashboard is struggling a bit in Chrome... I am going through and optimizing some of the biggest gifs, would you mind using this one instead of yours, it is not as high quality but still pretty good and 4 MB instead of 30 MB. Sorry for the trouble.

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/4560057/107169482-cbb8b480-6972-11eb-810f-5bdd87df8737.gif)

**Comment by rachelywong** [comment]
the gifception gif has been fixed 😎

**Comment by joelostblom** [comment]
Perfect thank you! And I did also appreciate your gif name :laughing:
